name: Deploy to SmarterASP.NET

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-2022

    env:
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore "src/DeerTier.Web.sln"

      - name: Inject production connection string
        shell: pwsh
        run: |
          $configPath = "src\DeerTier.Web\Config\ConnectionStrings.config"
          [xml]$xml = Get-Content $configPath
          $node = $xml.connectionStrings.add | Where-Object { $_.name -eq "Database" }
          $node.connectionString = "${{ secrets.DB_CONNECTION_STRING }}"
          $xml.Save($configPath)

      - name: Build project
        run: msbuild "src\DeerTier.Web\DeerTier.Web.csproj" /p:Configuration=Release

      - name: Publish web project
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" `
            src\DeerTier.Web\DeerTier.Web.csproj `
            /p:Configuration=Release `
            /p:WebPublishMethod=FileSystem `
            /p:DeleteExistingFiles=true `
            /p:publishUrl=publish

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: publish/
          server-dir: /site1/
          dangerous-clean-slate: true
